### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-localstorage-wMUDce#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://mi-449-ss17-740-js-localstorage-wmudce-griffinmartin.surge.sh/) and meets the following criteria:

- [x] Includes a button that when clicked, will toggle the website between day and night themes
- [x] When a user changes the theme, their choice is remembered in `localStorage`
- [x] The class on the `body` element is always up-to-date with the current theme (either `day-theme` or `night-theme`) -- you can use `document.body.setAttribute('class', 'some-class-name')` to set the class on the `body`
- [x] When the body has the class `day-theme`, the background of the website is light-colored, with a darker color for the text
- [x] When the body has the class `night-theme`, the background of the website is a very dark color, with a lighter color for the text
- [x] Somewhere on the page, the user is told how many times they've visited the website (starting with `1` the first time)

**Comment by chrisvfritz** [comment]
Very nice work, as always! 🎉 🌟 💥  Some room for growth I found:

### Fragile counter code

When we get the counter from `localStorage`, remember we're actually storing it as a string. Fortunately, `++` coerces the variable's value into a number, but it's a bit dangerous to rely on that. For example, if `visitCounter` starts at `'1'` and then we updated:

``` js
visitCount++
```

to:

``` js
visitCount += 1
```

It _should_ do the same thing, but instead `visitCount` will now be the string `'11'`. Instead, let's use `parseInt` on the value we get from `localStorage` to make our code a bit more robust.

### `removeItem` not actually necessary before `setItem`

I noticed some cases where you're removing an item from `localStorage` before setting it:

``` js
window.localStorage.removeItem('flux', 'off')
document.body.setAttribute('class', 'flux-on')
window.localStorage.setItem('flux', 'on')
```

This actually isn't necessary, as `setItem` will just replace whatever was there before. It's similar to doing something like this when you want to reassign a variable:

``` js
greeting = undefined
greeting = 'bye'
```

### Saving `localStorage` data to a variable

There are a lot of cases where you're getting `flux` from `localStorage`:

``` js
window.localStorage.getItem('flux')
```

I think many of these are unnecessary. Typically, it's best to just get the value once at the beginning of a function, then assign it to a variable you can reuse.

For example, instead of:

``` js
if (window.localStorage.getItem('flux') === null) {
  toggleOn()
} else if (window.localStorage.getItem('flux') === 'off') {
  toggleOn()
} else if (window.localStorage.getItem('flux') === 'on') {
  toggleOff()
}
```

You could use:

``` js
var flux = window.localStorage.getItem('flux')
if (flux === null) {
  toggleOn()
} else if (flux === 'off') {
  toggleOn()
} else if (flux === 'on') {
  toggleOff()
}
```

This will run slightly faster, as it actually takes a tiny bit of time to get values from `localStorage`, which can add up if you're doing it every other line.

### More efficient `if` statements

Speaking of this `if` statement:

``` js
if (flux === null) {
  toggleOn()
} else if (flux === 'off') {
  toggleOn()
} else if (flux === 'on') {
  toggleOff()
}
```

I see a couple issues. First, the only possible values here are:

- `null`
- `'off'`
- `'on'`

Which means we can actually just shorten the last `else if` to an `else`:

``` js
if (flux === null) {
  toggleOn()
} else if (flux === 'off') {
  toggleOn()
} else {
  toggleOff()
}
```

No need to check what it equals, because by process of elimination, there's only one possibility left! But we can do even better. Recapping, these are the things we want to happen:

- When `null`, `toggleOn()`
- When `'off'`, `toggleOn()`
- When `'on'`,  `toggleOff()`
- In the unlikely scenario of any other value, probably `toggleOn()`?

So that means the _only_ time we'll `toggleOff()` is when `flux` is `'on'`. So we can shorten it to just:

``` js
if (flux === 'on') {
  toggleOff()
} else {
  toggleOn()
}
```

### Replacing `toggleOn` and `toggleOff` with a single `toggleFlux` function

Let's take a closer look the `toggleOn` and `toggleOff` function (I removed the `removeItem` lines to simplify things):

``` js
// Toggles flux on and modifies localStorage
function toggleOn () {
  document.body.setAttribute('class', 'flux-on')
  window.localStorage.setItem('flux', 'on')
}

// Toggles flux off an modifies localStorage
function toggleOff () {
  document.body.setAttribute('class', 'flux-off')
  window.localStorage.setItem('flux', 'off')
}
```

The only difference between `toggleOn` and `toggleOff` here are the strings `'on'` or `'off'`. So instead, see if you can _replace_ these by a new `toggleFlux` function that fetches the `flux` from `localStorage`, then updates it:

``` js
function toggleFlux () {
  // 1. Get flux from localStorage
  // 2. Figure out what the newFlux should be
  // 3. Save the newFlux into localStorage
  updateTheme()
}
```

We'll talk about this `updateTheme` function in a second. 🙂  First, note that this simplifies our event listener to:

``` js
fluxButton.addEventListener('click', toggleFlux)
```

### Further simplifying with an `updateTheme` function

This code in `init`:

``` js
// Retrieve and set localStorage class
window.localStorage.getItem('flux')
if (window.localStorage.getItem('flux') === 'off') {
  toggleOff()
} else if (window.localStorage.getItem('flux') === 'on') {
  toggleOn()
}
```

Isn't really necessary if we just bypass any toggle functions with a separate `updateTheme` like this:

``` js
function updateTheme () {
  // 1. Get the flux from localStorage
  // 2. Update the `body` class with the current flux
}
```

With that in place, we could replace all flux-related code in `init` with just `updateTheme`! We can also use this same function in the new `toggleFlux` function, as we saw above.

---

I figured we could work on this stuff first, then I'll check in with you about a couple other ideas I have and see if you're interested. 😄

**Comment by GriffinMartin** [comment]
Updated! 
Was a little confused on what to do with the counter!
Thanks for all the advice 👍 
Let me know what other ideas you have 😃

**Comment by chrisvfritz** [comment]
Nice work! 🌟  I think I'll actually save the Vue trick for after our objects lesson, but I have some other notes for growth below:

### Noticing some quirkiness

In your hosted site, it looks like the button sometimes has to be pressed _twice_ now for the theme to actually change. See if you can investigate why this is. If you get stuck, I'm happy to help. 🙂 

### Using fallback values

For `visitCount`, we can actually simplify this code a little:

``` js
var visitCount = window.localStorage.getItem('counter')
if (visitCount === null) {
  visitCount = 0
}
parseInt(visitCount++)
```

If we use the fallback values (using `||`) that we learned about in the lesson about `if` statements, then we can cut this down to:

``` js
var visitCount = parseInt(window.localStorage.getItem('counter')) || 0
visitCount++
```

Since `parseInt(null)` will produce `NaN` (which is falsy) and the only falsy number is `0`, we now guarantee that `visitCount` will be a number, because any falsy value will fall back to `0`.

And a separate, but related note: In `parseInt(visitCount++)`, the `parseInt` wasn't actually doing anything. That's because `++` will automatically convert `visitCount` to a number if it isn't already. You'll want to use `parseInt` earlier to ensure that it's a number _before_ you start doing math with it, because as mentioned before, something like:

``` js
visitCount + visitCount + 1
```

or:

``` js
visitCount += 1
```

Would actually _convert the `1` into a string_ if `visitCount` isn't already a number. Does that make more sense?

### New trick: ternaries

There's an alternative way to write:

``` js
if (something) { 
  A
} else { 
  B
}
```

That's with a "ternary":

``` js
something ? A : B
```

You can read the `?` as "if the thing to the left of me, then return the thing to the right of me" and the `:` can be read as "else". Ternaries are best to avoid in most situations, since they can be more difficult to read for complex conditions. In simple cases though, they have an advantage of actually _returning_ `A` or `B` so we can use that value immediately. 

For example, in this case:

``` js
if (flux === 'on') {
  window.localStorage.setItem('flux', 'off')
} else {
  window.localStorage.setItem('flux', 'on')
}
```

We can use a ternary to shorten it to:

``` js
var newFlux = flux === 'on' ? 'off' : 'on'
window.localStorage.setItem('flux', newFlux)
```

Or even:

``` js
window.localStorage.setItem('flux', flux === 'on' ? 'off' : 'on')
```

This is _completely_ a stylistic decision. Some find this code more readable - others hate it. The main reason I introduce it is not to suggest you change what you currently have, but to show you an alternative that you'll commonly see in the wild.

---

As always, let me know if you have any questions/comments/etc. 😄

**Comment by GriffinMartin** [comment]
@chrisvfritz 
Thanks again!
I switched some things around and I fixed having to press the button twice on the initial load.
I used this to figure it out: http://stackoverflow.com/questions/542247/button-needs-to-be-clicked-twice-to-trigger-function
And solved it by adding newFlux to be outside as well as in the function. Is this the way you had intended?

**Comment by chrisvfritz** [comment]
### Noticing some quirkiness

The bug actually still exists. If `flux` in `localStorage` starts at `'off'`, you'll have to press the button _twice_ for the page to switch to `'on'` - and then when you refresh, it'll be off again! 

I would undo your last change and in this case, instead of Googling for the answer (which is often a great strategy! 👍 ), try using `console.log` at various points in your program and inspecting what's in `localStorage` with  `localStorage.valueOf()` in the browser's JavaScript console.

The solution in this case will come from walking through your program and figuring out where we're going out of sync, rather than learning any new techniques.

### Using fallback values

It looks like the fallback for the `visitCount` wasn't implemented _quite_ correctly:

``` js
var visitCount = window.localStorage.getItem('counter' || 0)
```

Breaking it down:

``` js
'counter' || 0
```

Will actually _always_ return `'counter'` because as a non-empty string, it will _always_ be truthy. That means it will actually do the same as just:

``` js
var visitCount = window.localStorage.getItem('counter')
```

We've also now lost `parseInt` entirely. Take another look at my previous comments about this and let me know if you have any questions! I want to make sure you understand the concepts behind this, so that you can successfully apply them in the future. 🙂

**Comment by GriffinMartin** [comment]
@chrisvfritz 
visitCounter updated.
I fixed the bug of having to press the button twice.
I also fixed an bug I discovered of localStorage not loading the last theme used on refresh.

Hopefully this looks good :)
Thanks!!!

**Comment by chrisvfritz** [comment]
🎉  _Yes!!_ 🎉  Looks great. 😄 :shipit: 🚀 🎈
